version: 2
jobs:
  build:
    environment:
      # Configure the JVM and Gradle to avoid OOM errors
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - run:
          name: Run tests
          command:
            ./gradlew test
      - store_test_results:
          path: build/test-results/test
      - store_artifacts:
          path: build/test-results/test
          when: always
      - run:
          name: Assemble JAR
          command:
            ./gradlew assemble
      - store_artifacts:
          path: build/libs
      - run:
          name: Deploy to Heroku
          command:
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
workflows:
  version: 2
  workflow:
    jobs:
    - build